name: noaa-haskell
version: 0.1.0.0
github: "hubbards/noaa-haskell"
license: BSD3
author: "Spencer Hubbard"
maintainer: "hubbardspencerm@gmail.com"
copyright: "2020 Spencer Hubbard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/hubbards/noaa-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- http-conduit
- time

library:
  source-dirs: src

executables:
  noaa-haskell-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - noaa-haskell

tests:
  noaa-haskell-test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - noaa-haskell
    - HUnit
